### ISSUE TITLE
Dock viewports into main platform window

### ISSUE THREAD

**Issue by Alex-Beh** [koide3/iridescence#103]
Hi, thanks for open source this great library.

The docking between the viewports have no issue. May I know how to dock the viewport into the main window?

**Comment by koide3** [comment]
Possibly you can do it with `ImGui::DockSpaceOverViewport()`. I forgot details but I think you can find the way to do it [here](https://github.com/ocornut/imgui/blob/88dfd85e9296fc03ac858f66cc6507ba443294ef/imgui_demo.cpp#L7829).
