### ISSUE TITLE
NormalDistributions class doesn't work when try to visualizer 2185 elipsoids.

### ISSUE THREAD

**Issue by mertyavuz41** [koide3/iridescence#112]
Hi Koide,

Thanks for your great work.

I'm trying to visualize normal distributions of a point cloud but I observed that the NormalDistributions class doesn't visualize upper than 2184 normal distributions but old version of this class(NormalDistributions_old) works fine. I don't have enough knowledge about OpenGL, so its hard to find what is the core of problem. I just wanted to inform you that there is a exist problem with NormalDistributions class.

Thanks,

**Comment by mertyavuz41** [comment]
As far as I understand, its related with 'local_size' value and this value depends on computer hardware capability. I increased local_size_x 32 to 1792(this is maximum value for my computer) and I can visualize more object using by NormalDistributions class.

https://github.com/koide3/iridescence/blob/d63014e08b727bf37222b16b734432690dc0e255/data/shader/transform_normal_dists_indices.comp#L3

https://github.com/koide3/iridescence/blob/d63014e08b727bf37222b16b734432690dc0e255/data/shader/transform_normal_dists_vertices.comp#L3

https://github.com/koide3/iridescence/blob/d63014e08b727bf37222b16b734432690dc0e255/src/glk/normal_distributions.cpp#L57

**Comment by koide3** [comment]
Thank you for reporting the issue. It should stem from OpenGL driver related problems as you said. 

Could you share what GPU model you are using? I'm thinking of tuning grouping parameters and/or falling back to the old version, which uses CPU to create normal distribution objects, on some GPUs.

**Comment by mertyavuz41** [comment]
Here the hardware informations I use;

GPU: GeForce RTX 2070 Mobile 
CPU: Intel® Core™ i7-8750H CPU @ 2.20GHz × 12
