### ISSUE TITLE
Adjusting Opacity of drawables

### ISSUE THREAD

**Issue by mertyavuz41** [koide3/iridescence#113]
Hello,

I wonder that are there any way to adjust opacity level of any drawable objects? I tried to set alpha values of color mode but it didn't work to set opacity.

**Comment by koide3** [comment]
To draw objects with transparency, you need to call `ShaderSetting::make_transparent()` like:

```cpp
viewer->update_sphere("sphere", guik::FlatColor(1.0, 0.0, 0.0, 0.5).make_transparent());
```

Then, the alpha value should be enabled.

**Comment by mertyavuz41** [comment]
> To draw objects with transparency, you need to call `ShaderSetting::make_transparent()` like:
> 
> ```c++
> viewer->update_sphere("sphere", guik::FlatColor(1.0, 0.0, 0.0, 0.5).make_transparent());
> ```
> 
> Then, the alpha value should be enabled.

This solves the relevant issue, thank you!
