### ISSUE TITLE
Error CMake with new version

### ISSUE THREAD

**Issue by LulaSan** [koide3/iridescence#136]
Hello, I was using your code in direct_visual_calibration and I realized lately was not working anymore giving this error on the cmake:
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Iridescence (missing: Iridescence_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIridescence.cmake:16 (find_package_handle_standard_args)
  CMakeLists.txt:52 (find_package)


---
Failed   <<< direct_visual_lidar_calibration [2.80s, exited with code 1]
                                
Summary: 0 packages finished [2.95s]
  1 package failed: direct_visual_lidar_calibration
  1 package had stderr output: direct_visual_lidar_calibration
  ```
  And I really tried everything to add these libraries, that were actually there.
  So, I realized the code was updated and switched back to this commit (#115 ) and now it is working

**Comment by koide3** [comment]
Thank you for reporting the issue.
The error should be resolved by removing `cmake/FindIridescence.cmake` in the calibration package. I'll fix it later.
