### ISSUE TITLE
Found includes for boost library in glk/cuda_magic_headers.hpp

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#138]
Hi Koide,
I was looking into the code and found that there are still inclusions from the boost library. But I think boost dependency should be removed several weeks ago, please check.

Thanks

**Comment by koide3** [comment]
Hi @Seekerzero ,
The header file includes some hpps to prevent build errors on old CUDA environments, and is no longer necessary and no longer used. I'll delete it later as it is not used by any code now.
