### ISSUE TITLE
error in cmake new version

### ISSUE THREAD

**Issue by JiangWeiHn** [koide3/iridescence#139]
cmake .. -DCMAKE_BUILD_TYPE=Release
CMake Deprecation Warning at /usr/lib/cmake/glm/glmConfig.cmake:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)
CMake Deprecation Warning at /usr/lib/cmake/glm/glmConfig.cmake:2 (cmake_policy):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimpTargets.cmake:54 (if):
  if given arguments:
    "ON"
  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  CMakeLists.txt:36 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

 I have  try to  follow https://github.com/assimp/assimp/issues/3222:
      IF(POLICY CMP0012)
          CMAKE_POLICY(SET CMP0012 NEW)
      ENDIF() 
But it does not work.My cmake version 3.30.3

**Comment by koide3** [comment]
I tried cmake 3.30.3, but the error didn't reproduce on Ubuntu 24.04. What is the ubuntu version you are using?

**Comment by JiangWeiHn** [comment]
My ubuntu version is 20.04,with ros1.

**Comment by Seekerzero** [comment]
The cmake was not correctly installed. Could you print the cmake version in the terminal? If it is 3.30.3, could you try switching to the older release?

**Comment by JiangWeiHn** [comment]
ok,i will try.
