### ISSUE TITLE
3D SLAM w/ texture

### ISSUE THREAD

**Issue by grassjelly** [koide3/iridescence#34]
Hi, just wondering which algorithm did you use to generate texture for the 3D point cloud found here 
![](https://user-images.githubusercontent.com/31344317/210128635-2ef02dff-3d74-499e-bde8-2c9c0dc047ff.jpg) .Thank you!

**Comment by koide3** [comment]
We didn't do SLAM but used a high-grade LiDAR (FARO focus) to take the colored point cloud.

**Comment by grassjelly** [comment]
Thank you!
