### ISSUE TITLE
Avoid ambiguity of GridMap

### ISSUE THREAD

**Issue by Tomoya-Sato** [koide3/iridescence#39]
Hi, thank you for your great repository!

I plan to make a PR about GridMap to add new constructor with that we can set RGBA independently and directly.
The statement is [here](https://github.com/Tomoya-Sato/iridescence/blob/feature/grid_map/include/glk/gridmap.hpp#L17) and the definition is [here](https://github.com/Tomoya-Sato/iridescence/blob/feature/grid_map/src/glk/gridmap.cpp#L71).
As you can see, I added a extra bool argument to avoid ambiguity, but it's not smart I think. Then, what do you think is the best way to avoid this ambiguity?

**Comment by koide3** [comment]
Hi @Tomoya-Sato ,

I would be happy to receive a PR for this.
In this case, it may be good to add a new color mode like ```RGBA``` and let the first constructor handle raw RGBA data.

**Comment by Tomoya-Sato** [comment]
Thank you @koide3
I'll follow your advice. Look forward to PR!
