### ISSUE TITLE
file dialog doesn't work when running iridescence in docker

### ISSUE THREAD

**Issue by juliangaal** [koide3/iridescence#52]
The file dialog needed for e.g. the point cloud visualization example doesn't open when using iridescence in docker on my machine. Have you experienced this issue before?

**Comment by n-patiphon** [comment]
@juliangaal It seems like [portable-file-dialogs](https://github.com/samhocevar/portable-file-dialogs) looks for Zenity (or KDE Kdialog) if it's used on Linux, as you can see [here](https://github.com/samhocevar/portable-file-dialogs/blob/ece1202552b887bb2dc72d0364f5b2069639e53c/portable-file-dialogs.h#L465). If you compile this project locally, there would be no problem as Zenity is installed with the desktop version (assuming Ubuntu) by default. However, Zenity doesn't seem to be included in the base image.

I opened a PR [here](https://github.com/koide3/iridescence/pull/53). Could you try if that PR fixes your issue?

**Comment by juliangaal** [comment]
Thank you, great catch! Works like a charm.
