### ISSUE TITLE
Docking/Layout

### ISSUE THREAD

**Issue by juliangaal** [koide3/iridescence#54]
I am trying to visualize a pointcloud and image side-by-side. At the moment, my gui looks like this:

![default](https://github.com/koide3/iridescence/assets/22290570/55eb501e-6d90-4023-8e2a-9960fc867ad9)

With [docking enabled](https://github.com/ocornut/imgui/wiki/Docking), I can modify the layout to 

![docked](https://github.com/koide3/iridescence/assets/22290570/09df8deb-eae7-4c96-8898-058ea91a0df9)

Now, I am not sure if this is an imgui or iridescence specific issue (feel free if to close if it's strictly imgui): How can I dock the pointcloud window the others [like see here](https://user-images.githubusercontent.com/8225057/97541627-c0dea300-19c5-11eb-9416-8bb255e189a1.png) (the "Game" window docked to the interface). 

Thanks

**Comment by juliangaal** [comment]
Thanks for your suggestions!

I think you misunderstood me slightly. I am looking to render the image next to the 3d object/cloud *inside* the main canvas. What would be the best approach, something [like this](https://github.com/ocornut/imgui/issues/3228)?

**Comment by koide3** [comment]
I may still be misunderstanding the question, but if you want to render images and 3D objects side-by-side, you can create a `guik::LightViewerContext` and show its rendering result next to another window showing an image using `ImGui::Dockspace`. 

![Screenshot_20230702_212321](https://github.com/koide3/iridescence/assets/31344317/66b42725-908e-417a-b782-a22af736901a)

```cpp
#include <iostream>
#include <guik/viewer/light_viewer.hpp>
#include <imgui_internal.h>

int main(int argc, char** argv) {
  auto viewer = guik::viewer();
  ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_DockingEnable;

  // Set up the dockspace before first UI callback
  viewer->invoke([] {
    ImGuiID dock_id = ImGui::GetID("my_dockspace");

    ImGui::DockBuilderRemoveNode(dock_id);
    ImGui::DockBuilderAddNode(dock_id);
    ImGui::DockBuilderSetNodeSize(dock_id, {1200, 600});

    ImGuiID right_id, left_id;
    ImGui::DockBuilderSplitNode(dock_id, ImGuiDir_Right, 0.5f, &right_id, &left_id);

    ImGui::DockBuilderDockWindow("left_window", left_id);
    ImGui::DockBuilderDockWindow("right_window", right_id);

    ImGui::DockBuilderFinish(right_id);
  });

  // Create a viewer context
  guik::LightViewerContext context("my_context");
  if (!context.init_canvas({512, 512})) {
    std::cerr << "error: failed to init viewer context!!" << std::endl;
    return 1;
  }
  context.update_wire_sphere("wire_sphere", guik::Rainbow());

  // UI callback
  viewer->register_ui_callback("ui_callback", [&] {
    // Update GL-related things in the context
    context.draw_gl();
    auto& canvas = context.get_canvas();

    // Begin a window to render the rendering result of the created viewer context
    ImGui::Begin("left_window", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
    ImGuiWindowFlags flags = ImGuiWindowFlags_ChildWindow | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoTitleBar |
                             ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoNavFocus;
    ImGui::BeginChild("canvas", ImVec2(canvas.size[0], canvas.size[1]), false, flags);

    // Mouse control
    if (ImGui::IsWindowFocused()) {
      canvas.mouse_control();
    }

    // Draw the image rendered by the context
    ImGui::Image((void*)canvas.color_buffer().id(), {512, 512}, {0, 1}, {1, 0});
    ImGui::EndChild();
    ImGui::End();

    // Begin another window to render the rendering result of the main viewer context
    ImGui::Begin("right_window", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
    ImGui::BeginChild("canvas2", ImVec2(canvas.size[0], canvas.size[1]), false, flags);
    ImGui::Image((void*)viewer->get_canvas().color_buffer().id(), {512, 512}, {0, 1}, {1, 0});
    ImGui::EndChild();
    ImGui::End();
  });

  viewer->spin();

  return 0;
}
```

**Comment by koide3** [comment]
Or if you mean you want to superimpose an image on the main viewer, you can use `guik::HoveredDrawings::add_image()` that renders an image on a specific 3D position (see `02_light_viewer_primitives.cpp`).

**Comment by juliangaal** [comment]
> Or if you mean you want to superimpose an image on the main viewer, you can use `guik::HoveredDrawings::add_image()` that renders an image on a specific 3D position (see `02_light_viewer_primitives.cpp`).

Yes! That sounds more like it. "Superimpose". Thanks, I'll check it out

**Comment by Alex-Beh** [comment]
@koide3 Hi, can I dock the two windows to the main windows?

similar ticket: https://github.com/ocornut/imgui/issues/5086

> I may still be misunderstanding the question, but if you want to render images and 3D objects side-by-side, you can create a `guik::LightViewerContext` and show its rendering result next to another window showing an image using `ImGui::Dockspace`.
> 
> ![Screenshot_20230702_212321](https://private-user-images.githubusercontent.com/31344317/250356225-66b42725-908e-417a-b782-a22af736901a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzQyODUsIm5iZiI6MTcxMzE3Mzk4NSwicGF0aCI6Ii8zMTM0NDMxNy8yNTAzNTYyMjUtNjZiNDI3MjUtOTA4ZS00MTdhLWI3ODItYTIyYWY3MzY5MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5Mzk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNGY2NTRiODhiMTBhMDAwOTJiOWQ2ODQ0NDE3MWU3NWY5OWNkN2IzODNkZDQzODBiNWZkY2QxMDUwNGUxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YOZfMTh-FrufgGU20w7l_f1jL3-Sq47khs4P1tBPI3o)
> 
> ```c++
> #include <iostream>
> #include <guik/viewer/light_viewer.hpp>
> #include <imgui_internal.h>
> 
> int main(int argc, char** argv) {
>   auto viewer = guik::viewer();
>   ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_DockingEnable;
> 
>   // Set up the dockspace before first UI callback
>   viewer->invoke([] {
>     ImGuiID dock_id = ImGui::GetID("my_dockspace");
> 
>     ImGui::DockBuilderRemoveNode(dock_id);
>     ImGui::DockBuilderAddNode(dock_id);
>     ImGui::DockBuilderSetNodeSize(dock_id, {1200, 600});
> 
>     ImGuiID right_id, left_id;
>     ImGui::DockBuilderSplitNode(dock_id, ImGuiDir_Right, 0.5f, &right_id, &left_id);
> 
>     ImGui::DockBuilderDockWindow("left_window", left_id);
>     ImGui::DockBuilderDockWindow("right_window", right_id);
> 
>     ImGui::DockBuilderFinish(right_id);
>   });
> 
>   // Create a viewer context
>   guik::LightViewerContext context("my_context");
>   if (!context.init_canvas({512, 512})) {
>     std::cerr << "error: failed to init viewer context!!" << std::endl;
>     return 1;
>   }
>   context.update_wire_sphere("wire_sphere", guik::Rainbow());
> 
>   // UI callback
>   viewer->register_ui_callback("ui_callback", [&] {
>     // Update GL-related things in the context
>     context.draw_gl();
>     auto& canvas = context.get_canvas();
> 
>     // Begin a window to render the rendering result of the created viewer context
>     ImGui::Begin("left_window", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
>     ImGuiWindowFlags flags = ImGuiWindowFlags_ChildWindow | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoTitleBar |
>                              ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoNavFocus;
>     ImGui::BeginChild("canvas", ImVec2(canvas.size[0], canvas.size[1]), false, flags);
> 
>     // Mouse control
>     if (ImGui::IsWindowFocused()) {
>       canvas.mouse_control();
>     }
> 
>     // Draw the image rendered by the context
>     ImGui::Image((void*)canvas.color_buffer().id(), {512, 512}, {0, 1}, {1, 0});
>     ImGui::EndChild();
>     ImGui::End();
> 
>     // Begin another window to render the rendering result of the main viewer context
>     ImGui::Begin("right_window", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
>     ImGui::BeginChild("canvas2", ImVec2(canvas.size[0], canvas.size[1]), false, flags);
>     ImGui::Image((void*)viewer->get_canvas().color_buffer().id(), {512, 512}, {0, 1}, {1, 0});
>     ImGui::EndChild();
>     ImGui::End();
>   });
> 
>   viewer->spin();
> 
>   return 0;
> }
> ```
