### ISSUE TITLE
The issue of getting stuck during Docker runtime

### ISSUE THREAD

**Issue by zyqaq61616** [koide3/iridescence#59]
When I am running Docker and visualizing the results on my host, the GUI interface becomes very sluggish and even unable to move or rotate. May I ask what is the reason for this，
My Docker Parameters
-it \
--ipc=host \
--gpus all \
-e DISPLAY=$DISPLAY \

**Comment by koide3** [comment]
Try `nvidia/opengl:1.0-glvnd-runtime-ubuntu20.04` docker image to run OpenGL applications with hardware acceleration on docker.

**Comment by zyqaq61616** [comment]
thanks
