### ISSUE TITLE
drawing bounding box.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#63]
Is it possible to use this tool to draw a bounding box for a point cloud? If so, could you provide an example code?
Thanks.

**Comment by n-patiphon** [comment]
I've never tried it, but I think you should be able to use a combination of [pcl::getMinMax3D](https://pointclouds.org/documentation/group__common.html#gafd9010977f5e52b35b484be7624df3f8) and `glk::Primitives::cube();` to visualize the bounding box of a point cloud pretty easily.

**Comment by Seekerzero** [comment]
Thanks for your answer. However, what I want is to draw a bounding box within a point cloud (sorry for unspecific description previously), so that I can crop out, or label a specific cluster of points.

**Comment by koide3** [comment]
Possibly this example is something you want?
https://koide3.github.io/iridescence/cookbook/

**Comment by Seekerzero** [comment]
This could be really helpful. I will try this with some editions. Thanks.
