### ISSUE TITLE
Adding icon fonts

### ISSUE THREAD

**Issue by n-patiphon** [koide3/iridescence#64]
Has anyone tried to import icon fonts to Iridescence? More specifically, using the [AwesomeFont](https://github.com/juliettef/IconFontCppHeaders#example-code).

I have tried loading TFF file in the main ui callback, but it didn’t seem to work. I understand that it’s mostly related to imgui, however, I figured I should ask here in case anyone was trying to do the same thing.

Please feel free to close this if you think it’s irrelevant. 🙏

**Comment by koide3** [comment]
I've not tried this yet, but it sounds very cool. I suppose the awesome font initialization can be done just after the first creation of the viewer instance, and is not necessary to be in a UI callback. I would like to have a try in a spare time.

**Comment by n-patiphon** [comment]
Thank you for your reply. I also tried initializing the font just after creating the viewer instance. However, the glyphs were not loaded. 

I kind of gave up on loading the TTF file and use ImageButton instead. If you figure it out, I would be really interested to know.

By the way, I found that ImageButton’s texture doesn’t render **unless** I also call update_image from guik. Maybe it’s just me not knowing my way around ImGui and OpenGL that well.

**Comment by koide3** [comment]
I found that the loaded fonts are enabled by calling `io.Fonts->Build();` after `io.Fonts->AddFontFromFileTTF();`. I also put TTF files in the executable directory (I'm not sure if ImGui can load system installed fonts...). 

Regarding the texture issue, if you could provide a short code to reproduce the issue, I would like to dig into the problem.

![Screenshot_20231025_184905](https://github.com/koide3/iridescence/assets/31344317/4061be99-0bb1-462f-a406-15c2e672f3f1)

```cpp
#include <guik/viewer/light_viewer.hpp>

#include <IconsFontAwesome6.h>

int main(int argc, char** argv) {
  auto viewer = guik::viewer();

  auto& io = ImGui::GetIO();

  io.Fonts->AddFontDefault();

  float baseFontSize = 13.0f;
  float iconFontSize = baseFontSize * 2.0f / 3.0f;

  static const ImWchar icons_ranges[] = {ICON_MIN_FA, ICON_MAX_16_FA, 0};
  ImFontConfig icons_config;
  icons_config.MergeMode = true;
  icons_config.PixelSnapH = true;
  icons_config.GlyphMinAdvanceX = iconFontSize;
  io.Fonts->AddFontFromFileTTF(FONT_ICON_FILE_NAME_FAS, iconFontSize, &icons_config, icons_ranges);
  io.Fonts->Build();

  viewer->register_ui_callback("ui_callback", [] {
    ImGui::Text(ICON_FA_HOUSE " HELLO " ICON_FA_HOUSE);
  });

  viewer->spin();
  return 0;
}
```

**Comment by n-patiphon** [comment]
Thank you very much! Yes, I think this is it. I didn't call `Build()`.  I will try later. If it works, I think this can be closed.

About the image, when I tried to create a minimum working example, I couldn't reproduce it. I think it was how I managed the texture. The created texture was probably out of scope. Please ignore this problem for the time being.

**Comment by n-patiphon** [comment]
The solution worked! I really needed to call Build. Thank you so much for taking the time to check this. I'm closing this issue.

Thank you again!
