### ISSUE TITLE
error on compile

### ISSUE THREAD

**Issue by gyillikci** [koide3/iridescence#66]
Hello,

I am having the error below while building from source and couldn't find fix for it 

error: ‘glfwGetMonitorWorkarea’ was not declared in this scope; did you mean ‘glfwGetMonitorName’?
  776 |         glfwGetMonitorWorkarea(glfw_monitors[n], &x, &y, &w, &h);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         glfwGetMonitorName

![image](https://github.com/koide3/iridescence/assets/5228976/29d62259-04bd-45a9-b31f-8cd118e91dec)

**Comment by n-patiphon** [comment]
Did you `sudo apt install -y libglfw3-dev`?

**Comment by gyillikci** [comment]
yes,

its already installed 
![image](https://github.com/koide3/iridescence/assets/5228976/431d6e78-a2b7-4d66-ab08-1a9857ed9f7f)

**Comment by koide3** [comment]
What is your OS version?

**Comment by hitwdy** [comment]
I'm also getting this error on ubuntu20 04

**Comment by gyillikci** [comment]
I am having this issue on Jetson Orin NX ubuntu20.04

**Comment by gyillikci** [comment]
on the newer version of jetpack 5.1.2, the problem solved
![image](https://github.com/koide3/iridescence/assets/5228976/319babb9-6e46-4b5b-ad36-e87a8769945b)

**Comment by edwardes2201** [comment]
// Reemplaza esta línea en imgui_impl_glfw.cpp
// glfwGetMonitorName(glfw_monitors[n], &x, &y, &w, &h);
// con estas líneas
const char* monitorName = glfwGetMonitorName(glfw_monitors[n]);
const GLFWvidmode* vidMode = glfwGetVideoMode(glfw_monitors[n]);
x = 0;
y = 0;
w = vidMode->width;
h = vidMode->height;
