### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Xuanyaiiii** [koide3/iridescence#68]
iridescence/src/glk/glsl_shader.cpp:289:36: error: cannot bind non-const lvalue reference of type ‘std::__cxx11::basic_string<char>&’ to an rvalue of type ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’
     boost::split(error_lines, std::string(error_message.begin(), error_message.end()), boost::is_any_of("\n"));

how to solve this question

**Comment by Seekerzero** [comment]
Did you compile it through the c++14 standard or the later version? I think cxx11 does not support non const lvalue references.
