### ISSUE TITLE
camera Keyboard control speed adjustment and get mouse pose from subviewer.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#73]
Hi,
I am trying to figure out moving the camera with the keyboard, but it seems like the moving speed with ctrl+up(down, left, right) is kinda slow. Is there any way to adjust the camera's moving speed? Also, it would be helpful if we could get an instruction on keyboard control for the viewer. Maybe it is hidden somewhere lol.

Also, I noticed that you show an example of getting the mouse position using register callback; however, it seems like the subviewer class can't register a UI callback (I am using the Python binding). Do you know if there is any way to achieve that?

Thanks!

**Comment by koide3** [comment]
Thanks for your feedback.

For now, the keyboard camera control is preliminary and does not have speed adjustment capability, but I will soon add some supports (and documentation) for better keyboard camera control.

In case of C++, you can register a callback to a sub viewer and find clicked positions like in the following snippet. I'll expose this interface to the python binding later.

```cpp
auto viewer = guik::viewer();
auto sub_viewer = viewer->sub_viewer("sub_viewer");
sub_viewer->update_cube("cube", guik::Rainbow());

// Register a UI callback to the sub_viewer
sub_viewer->register_ui_callback("sub_viewer_ui_callback", [=] {
  auto& io = ImGui::GetIO();

  // We would need some more conditions to check if the mouse is on the sub_viewer window
  if (io.MouseClicked[ImGuiMouseButton_Right]) {
    const auto winpos = ImGui::GetWindowPos();
    const Eigen::Vector2i clicked_pos = {io.MousePos.x - winpos.x, io.MousePos.y - winpos.y};

    const float depth = sub_viewer->pick_depth(clicked_pos);
    if (depth > 0.0) {
      const auto pt = sub_viewer->unproject(clicked_pos, depth);
      sub_viewer->update_sphere("sphere", guik::FlatRed().translate(pt).scale(0.1));
    }
  }
});

viewer->spin();
```

**Comment by Seekerzero** [comment]
Thanks for your quick response(I've seen your PR)! Looking forward to implementing these new features tomorrow!

**Comment by koide3** [comment]
I just merged the PR that implements an enhanced keyboard camera control and exposes a few UI methods to python bindings. Doc for the keyboard control can be found at https://koide3.github.io/iridescence/misc/#keyboard-shortcut.

Note that python bindings do not expose all the interfaces available in C++ for now, but I thin I will improve it later.

**Comment by Seekerzero** [comment]
Thank you! 
I just checked the new features, and the camera control works smoothly on my end. I will try to implement the new UI features later. 
Just one more small idea, maybe it would be great to set the keyboard_control_speed as a parameter for the camera_control class so that developers can set a value to it when they start the program (also for different control methods). And also it allows users to know how fast the camera is moving through the UI.

**Comment by koide3** [comment]
I think it's a good and reasonable idea. I'll implement it later. Note that the keyboard control is implemented by emulating mouse input internally, and it is also possible to move the camera by directly using mouse callback methods (`CameraControl::arrow` and `updown`).

https://github.com/koide3/iridescence/blob/adf42d73526654ea9780d2bd1894efc822fbf47a/include/guik/camera/camera_control.hpp#L25

**Comment by Seekerzero** [comment]
Gotcha. I am working on building an indoor point cloud explorer. In my case, using both keyboards to move and the mouse to change the view angle would be more intuitive. Currently, the keyboard control is pretty usable for my work. But in the future, I think we need some mechanism to define the keyboard state (input text, and moving standalone) to let the user move without keeping pressing the ctrl button so that the user can control the camera moving with the keyboard and mouse at the same time (WASD+mouse) like in video games.

**Comment by koide3** [comment]
It sounds good. I put this idea of video-game-like camera control in my TODO list. I also think it would be good to add documentation about how to implement a custom camera control using `guik::CameraControl` so that the user can move the camera in a way they want.

**Comment by Seekerzero** [comment]
Sounds good!

**Comment by koide3** [comment]
I implemented a FPS-game-like camera control with the following keyboard+mouse control. I hope this would be good for users doing indoor data inspection like you :)
![Screenshot_20240127_143125](https://github.com/koide3/iridescence/assets/31344317/44970d15-8052-4615-8479-d5e0bedefb1e)

**Comment by Seekerzero** [comment]
Thank you! I will check it on Monday and give you some feedback soon.

**Comment by Seekerzero** [comment]
I tested the new FPS camera control feature, and it works great! I think there is a minor issue that needs to be fixed: 1. it is lagging (the render process camera moves even when the user releases the key) when moving the keyboard and mouse simultaneously after loading a point. 2. The camera key control moving speed can slow down a bit (we might want the speed adjustment feature applied to this control method first.

**Comment by koide3** [comment]
Thanks for your feedback.
Regarding 2., I slightly updated `use_fps_camera_control()` so that it returns the `FPSCameraControl` instance and the user can easily change the camera moving speed:

```cpp
#include <guik/viewer/light_viewer.hpp>
#include <guik/camera/fps_camera_control.hpp>

int main(int argc, char** argv) {
  auto viewer = guik::viewer();

  auto camera = viewer->use_fps_camera_control();
  camera->set_translation_speed(0.01);
  camera->set_mouse_senstivity(0.005, 0.005);

  viewer->spin();

  return 0;
}
```

Regarding 1., do you mean that the camera keeps moving while the viewer is blocked by some processes?

**Comment by Seekerzero** [comment]
Thanks for updating the speed feature!
Regarding 1, yes, I think the render process is slowed down when moving inside a large set of point cloud (high density). So, when I drag the mouse and press the keyboard at the same time, sometimes the viewer will tend to process one motion first than others, (or it might just drop the input sometimes.
I think we might need to adapt a mechanism that drops the input that hasn't been processed after a certain time period, to prevent users have a laggy feeling.

**Comment by koide3** [comment]
I got it, and I think it should be easy to make the moving speed independent of the refresh rate using `ImGuiIO::DeltaTime`. I'll update the code in the next weekend.

**Comment by koide3** [comment]
I just pushed a commit to make the camera moving speed independent of the refresh rate https://github.com/koide3/iridescence/pull/77.

**Comment by Seekerzero** [comment]
I just tested the update, and it works perfectly on my end. I think we can merge this into the master branch and close the issue.

**Comment by koide3** [comment]
It's just merged! Your feedback was always very clear and helpful, and people like you greatly encourage me. Thanks a lot 👍
