### ISSUE TITLE
Unable to get the inputtext result out from the imgui pybinding inside the register ui.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#75]
Hi,
I was trying to use the pybinding for the imgui::inputtext (imgui.inputtext) inside the register_callback function and found an issue. The function returns (bool, str) as the result, but the str never gets what the user types in out, instead, it always returns the predefined value of the text parameters. This also happened in your light_viewer.py example.

I tested this function inside the cpp implementation, and it works. I guess the issue might be caused by a wrong buffer implementation.

Thanks.

**Comment by koide3** [comment]
Thanks for reporting the bug. I'll take a look at this soon.

**Comment by koide3** [comment]
I found that there was a bug regarding the  buffer update timing as you pointed out. I  will soon merge a fix https://github.com/koide3/iridescence/pull/78 . Thanks again for finding this bug!

**Comment by Seekerzero** [comment]
Thank you! I tested the updated inputtext() function on my end. It works properly right now. I think we can close this issue.
