### ISSUE TITLE
compute real point pose from mouse

### ISSUE THREAD

**Issue by xiaoxiaotao** [koide3/iridescence#82]
Hello,I have a point cloud map loaded, and now I want to edit this map. For example, I want to be able to draw lines, rectangles, and remove points from the point cloud. Additionally, I want to be able to obtain the pose of the mouse-clicked points. 
The pose is in the coordinate system of the point cloud map。
![1708483191165](https://github.com/koide3/iridescence/assets/11940219/54978602-90d7-42a6-ae23-29e7d5d7669b)
my point cloud map.

I take tutorial write code，
`    
main_canvas_->mouse_control();
    if (ImGui::IsMouseClicked(1))
    {
      auto mouse_pos = ImGui::GetMousePos();
      auto& io = ImGui::GetIO();
      auto winpos = ImGui::GetWindowPos();
      Eigen::Vector2i clicked_pos = {io.MousePos.x  -winpos.x, io.MousePos.y -winpos.y};

      const float depth = main_canvas_->pick_depth(clicked_pos);
      std::cout<<"depth "<<depth<<std::endl;
      std::cout<<"view  matrix "<<main_canvas_->camera_control->view_matrix()<<std::endl;
      std::cout<<"project  matrix "<<main_canvas_->projection_control->projection_matrix()<<std::endl;
      if(depth > 0.0)
      {
        const auto pt = main_canvas_->unproject(clicked_pos, depth);
        std::cout << "pt " << pt << std::endl;
      }
    }`

main_canvas_ is std::unique_ptr<guik::GLCanvas> main_canvas_;
However, the obtained depth is 1, the obtained pose may not be accurate.

**Comment by koide3** [comment]
You don't need to create `GLCanvas` by yourself to obtain the clicked position but you can register a callback function to the viewer and use `viewer->pick_point(1)` as in the following example.

```cpp
auto viewer = guik::viewer();

viewer->register_ui_callback("ui", [&] {
  int button = ImGuiMouseButton_Right;
  std::optional<Eigen::Vector3f> pt = viewer->pick_point(button);
  if (pt) {
    std::cout << "clicked point=" << pt->transpose() << std::endl;
  }
}
```
