### ISSUE TITLE
The grid on display can return pick points.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#83]
Hi koide, 
I just found that using viewer->pick_point(ImGuiMouseButton_Right) will return coordinates when clicking on the grid. Not sure if this is an intended design.

**Comment by koide3** [comment]
Yes, it returns coordinates of the clicked object wherever it is. If you want to distinguish clicked objects, it is necessary to use the info buffer.

**Comment by Seekerzero** [comment]
ok, in that case, I think I can disable the XY grids manually when I initialize the viewer.
