### ISSUE TITLE
Discussion about the Primitives properties

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#84]
Hello Koide,
I was trying the point picking on a point cloud. It seems like it is not really intuitive to set up some parameters of glk::Primitives in the shader setting, such as transform and scale.

It is reasonable to set the render scale inside the shader setting, but setting coordinates in splatting during initialization could be confusing to users. 

I think the design might be worth a discussion over the design. (such as whether to add a new parameter like transformation for the update_drawable function.)

Minor fix; it seems like the scale unit for **guik::VertexColor().set_point_scale(pointScale)** on point in pointcloud and **guk::FlatRed().scale(pointScale)** on primitives sphere are different; the second one is much larger from what I've seen. Probably adding a document would be helpful.

Thank you and Cheers!

**Comment by Seekerzero** [comment]
I think it would be great if we could have a mechanism for managing all the primitive coordinates in the global coordinate system. In my usage, most of the time the lifecycle of a primitive will consist multiple transformations until it gets removed, and only one shader setting at initialization. 

And for those need to be changed color settings multiple times (for me mostly about point cloud rendering), I would like to have the ability to partially update the splatting setting for a specific part of points (using indices).  Currently, it seems like it only supports partial rendering (e.g. some rendering vertex colors and some in red color). something like viewer->updating_pointcloud_colors_with_indices(name, indices, color_setting), or cloud_buffer->update_colors_with_indices(indices, color_setting).

I haven't looked deep into the primitive managing system (I guess currently you are tracking the primitives using their names, this is also one of the features we can improve in the future because the tracing with names would be hard to manage when doing group updating (multiple objects at once, all of them need to have a name, probably I am just too lazy lol)). But at least we don't want users to call update_drawable() hundreds of times inside viewer->spin_once(), a function that can handle group updating would be great for both user convenients and async rendering.

**Comment by koide3** [comment]
I agree with that grouping of objects would be useful. Maybe introducing a namespace mechanism like linux directory names would be nice? (e.g., a setting for `/foo/bar` affects all children like `/foo/bar/x` and `/foo/bar/baz/y`)

Because directly implementing this feature in `LightViewer` may require a large API change, I'm thinking of implementing a class to represent a group of objects in tree-structure like following one. Do you think if it would fit to your situation?

```cpp
class DrawableTree : public glk::Drawable {
  void set_setting(name, setting);
  void update_drawable(name, drawable, setting);
};

auto tree = make_shared<DrawableTree>();
viewer->update_drawable("tree", tree);

tree->set_setting("foo/bar", guik::FlatRed().scale(0.5));
tree->update_drawable("foo/bar/x", glk::Primitives::sphere(), guik::FlatGreen());  // Green sphere scaled by 0.5
tree->update_drawable("foo/bar/y", glk::Primitives::sphere(),  guik::FlatBlue().scale(0.5));  // Blue sphere scaled  by 0.5 * 0.5

tree->set_setting("foo/bar", guik::FlatRed().scale(0.25));  // Change all children scale
```

Regarding point colors, due to how OpenGL works, it is difficult to change the coloring scheme point-by-point (e.g., `FlatRed` to `VertexColor`) is difficult (very inefficient). Meanwhile, implementing something like `cloud_buffer->update_colors_with_indices` would be easy (I'll do), and it would work nice if you draw all points with `VertexColor`. Note that I often override point colors using `IndexedPointCloudBuffer` with slightly enlarged points like [this](https://youtu.be/pHPGS8VNN2o?si=4piW4CvzpDnaC9lL&t=30) and [this](https://koide3.github.io/iridescence/cookbook/).

**Comment by Seekerzero** [comment]
Thanks for sharing your thoughts!

Regarding the design of group management, yes I think it would be nice if we could manage a group of primitives by their names (we are making them like ROS topic lol). 

About the color updating, yes, something like `cloud_buffer->update_colors_with_indices` would be sufficient for me to achieve my current tasks.  I checked your example about updating points' color. It would work great when selection is not continuous, otherwise, we have to take care of the naming convention of the selected objects (going back to the previous problem). Also, I am not sure whether the implementation of `IndexedPointCloudBuffer` will add more points into the space (or it just simply updates the point cloud with the previous buffer), if so, we probably also don't want to do that with a condensed point cloud.

**Comment by koide3** [comment]
Yeah, the solution with `IndexedPointCloudBuffer` draws points twice that causes some overhead. I implemented methods to update point attributes with indices https://github.com/koide3/iridescence/pull/90 that may suffice for your situation.

```cpp
std::vector<Eigen::Vector4f> colors(num_indices);
std::vector<unsigned int> indices(num_indices);
cloud_buffer->update_color_with_indices(colors, indices);
```

I also implemented a feature to change the point scale and  shape configurations https://github.com/koide3/iridescence/pull/89. Doc: 
![Screenshot_20240317_010743](https://github.com/koide3/iridescence/assets/31344317/b5c84e15-4738-4f97-8142-e1c786fd7281)

**Comment by Seekerzero** [comment]
Hi Koide, 
I just tested the feature of update point scale mode. All of them look good to me on my end. Thanks again! 
And here are several suggestions that could be good to be updated before you merge the feature into the master.
1. little typo inside the document:  should be guik::PointShapeMode:CIRCLE corresponding to "point_shape_mode"
2. it would be good to align the naming convention between "point_size" and "point_radius". Since after user switched the mode, they still need to also change the term to update point size( e.g. setting up point_radius in screen space mode would do nothing, user might not figure out which part of the code is not working). we want to avoid this.

Other things look cool to me, the picture for comparing different modes looks fantastic.

**Comment by Seekerzero** [comment]
I also tested the partial points update on my end they work smoothly. Good job and thank you!
Some questions related to this feature:
1. Does this feature only work in VertexColor Mode?
2. How does it store the updated colors? Does it directly replace the original vertex color stored inside the buffer?
3. If the second question is true, it would be great to implement this feature as a "color_mask" on the vertex color, which stores the indices and mask_color separately, so that users can either activate the mask or close the mask.
 something like this:
```
cloud_buffer-> add_color_mask_with_indices(name, color, indices, show_mask=false); //user can choose whether to show the mask after adding it.
cloud_buffer-> remove_color_mask(name)
cloud_buffer-> hide_color_mask(name)
cloud_buffer-> show_color_mask(name)
```cpp

**Comment by koide3** [comment]
> little typo inside the document: should be guik::PointShapeMode:CIRCLE corresponding to "point_shape_mode"

Ah, thanks! I fixed it.

> it would be good to align the naming convention between "point_size" and "point_radius". Since after user switched the mode, they still need to also change the term to update point size( e.g. setting up point_radius in screen space mode would do nothing, user might not figure out which part of the code is not working). we want to avoid this.

At first, I thought using `point_size` for both the scaling modes would be confusing because they are based on different units (m vs pix). But, I agree that using two different but similar variables would be more confusing for users. I'll update the code so that both the modes use `point_size`.

**Comment by koide3** [comment]
> Does this feature only work in VertexColor Mode?

Yes, vertex colors are only applied to the VertexColor mode.

> How does it store the updated colors? Does it directly replace the original vertex color stored inside the buffer?

It directly overwrites vertex color data on the GPU buffer.

>  If the second question is true, it would be great to implement this feature as a "color_mask" on the vertex color, which stores the indices and mask_color separately, so that users can either activate the mask or close the mask.
something like this:

Hmmm, it would be a bit tricky to implement such a feature on the library side. Switching dynamic masks in a general way is a bit difficult on OpenGL. In this case, I would suggest having and updating a vertex color buffer (e.g., `std::vector<Eigen::Vector4f>`) on the user side and re-upload the entire (or a part) of the buffer to the GPU using `update_colors_with_indices`.

**Comment by Seekerzero** [comment]
Sounds good, I will test the naming convention when it is updated. 
Related to the mask, thanks for the info. Yes, in this case, the new feature `update_colors_with_indices` would be sufficient.
Thanks!

**Comment by koide3** [comment]
Thanks. Because it was a small modification, I already merged the update into the main branch. But I would be grateful if you could verify it. The doc with updated naming convention  is here https://koide3.github.io/iridescence/drawables/#point-scale.

**Comment by Seekerzero** [comment]
Hi Koide, 
I just tested the new adopting functions on my end. They all look good to me. Thanks! I think we can close this issue and open a new one for the drawable group management.
