### ISSUE TITLE
min max limit of fov for fpscamera control.

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#85]
Hello koide, 
it would be great to add three setups for the fovy value for fpscamera control: min, max, and default. And the possible related functions could be:
setupFOVMinMax(min, max, default=60)
resetFOV()  to default value
lockFOV()

Please let me know your ideas about this.

**Comment by Seekerzero** [comment]
Also on my side,  when I dragging the view toward the ground and passing through the angle vertical to the ground, the camera automatically flip point cloud along both x and y axes (to -x, -y), causing a reverse direction control from the keyboard (pressing w but moving backward).

**Comment by koide3** [comment]
Thanks for your request and reporting the camera control issue.

I think the fov angle configuration is reasonable and easy to implement. I will do it with some regulation of camera pose regulation later.

**Comment by Seekerzero** [comment]
Thanks!

**Comment by Seekerzero** [comment]
Hi koide, 
I just tested the new functions added to fpscamera control, works smoothly on my side. Thank you!

**Comment by koide3** [comment]
Thanks! It's just merged!
