### ISSUE TITLE
features to remove and hide sub-viewer

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#87]
Hi koide,
it would be great if we could set up some features for the sub-viewer from the LightViewer:
void viewer->remove_sub_viewer("sub_viewer_name")
void viewer->hide_sub_viewer("sub_viewer_name") // return true if the action is successfully proceed.
bool viewer->show_sub_viewer("sub_viewer_name")// return false if the sub_viewer does not exist

**Comment by koide3** [comment]
I just opened a PR https://github.com/koide3/iridescence/pull/88 to add the following methods. 

```cpp
auto viewer = guik::viewer();

viewer->remove_sub_viewer("sub");  // Returns false if sub viewer does not exist
auto sub = viewer->find_sub_viewer("sub");  // Returns nullptr if sub  viewer does not exit
sub->hide();  // Hide sub viewer (contents will remain)
sub->show();  // Show sub viewer
```

**Comment by koide3** [comment]
I also made  it possible to re-show subviewers from the viewer menu (Ctrl+M -> Display -> Show Sub Viewers).

**Comment by Seekerzero** [comment]
The updated features were tested on my side and work great. I think they are good to be merged into the main branch. Thanks again!

**Comment by koide3** [comment]
Thanks for testing. I merged it.
