### ISSUE TITLE
render hovered text and guizmo on subviewer

### ISSUE THREAD

**Issue by Seekerzero** [koide3/iridescence#91]
Hi Koide,
As mentioned in the title, I was not able to call out the hovered text on the subviewer, is this because these features are set default to be in the main viewer? Or I implemented them in a wrong way. 

Same as the guizmo, seems like it was default bind to the main viewer. 

Could you provide some interface to implement this on the subviewer? Or please show me some examples.

Thanks!

**Comment by koide3** [comment]
Both of HoveredDrawings and Guizmo can be drawn on the subviewer although it is not documented (my bad). Because Guizmo requires information on the window position and size, it requires a few lines of code as in the following. I noticed that HoveredDrawings requires a raw pointer of the viewer context that would be good and be fixed soon. 

```cpp
#include <guik/model_control.hpp>
#include <guik/hovered_drawings.hpp>
#include <guik/viewer/light_viewer.hpp>

int main(int argc, char** argv) {
  auto viewer = guik::viewer();

  // ModelControl
  auto sub = viewer->sub_viewer("sub");
  sub->disable_xy_grid();

  auto model_control = std::make_shared<guik::ModelControl>("model_control");
  sub->register_ui_callback("model_control", [=] {
    const ImVec2 canvas_rect_min = ImGui::GetItemRectMin();
    const ImVec2 canvas_rect_max = ImGui::GetItemRectMax();
    const Eigen::Matrix4f view_matrix = sub->get_camera_control()->view_matrix();
    const Eigen::Matrix4f projection_matrix = sub->get_projection_control()->projection_matrix();

    const int win_x = canvas_rect_min.x;
    const int win_y = canvas_rect_min.y;
    const int win_w = canvas_rect_max.x - canvas_rect_min.x;
    const int win_h = canvas_rect_max.y - canvas_rect_min.y;

    model_control->draw_gizmo(win_x, win_y, win_w, win_h, view_matrix, projection_matrix, true);

    sub->update_coord("coord", guik::VertexColor(model_control->model_matrix()));
  });

  // HoveredDrawings
  auto hovered = std::make_shared<guik::HoveredDrawings>(sub.get());  // Passing a raw pointer is bad... Need to add a shared_ptr interace.
  hovered->add_rect_on("coord", IM_COL32(0, 255, 0, 255));
  sub->register_ui_callback("hovered", hovered->create_callback());

  viewer->spin();

  return 0;
}
```

![Screenshot_20240331_220800](https://github.com/koide3/iridescence/assets/31344317/c984807d-8233-4408-8cfb-045054536dff)

**Comment by koide3** [comment]
I just merged an update that makes it possible to avoid passing a raw pointer to HoveredDrawings.

```cpp
auto hovered = std::make_shared<guik::HoveredDrawings>(sub);
hovered->add_rect_on("coord", IM_COL32(0, 255, 0, 255));
sub->register_ui_callback("hovered", hovered->create_callback());
```

**Comment by Seekerzero** [comment]
Hi Koide,
I just tested the feature for drawing Guizmo on the subviewer. The gizmo is successfully drawn on the subviewer. Thank you! But there are several problems I am encountering:
1. There isn't a protocol for setting up the gizmo mode directly.
2. The gizmo will not be able to hide once it is drawn on the screen.
3. The scale is not adjustable for the drawing lines (I might be wrong with this one).

Could you add some interfaces to handle these features？

Thanks!

**Comment by koide3** [comment]
1. I agree. There should be a way to change the gizmo mode. I'll  add some setters to `guik::ModelControl`.
2. To hide gizmo, you can just stop calling `draw_gizmo()` like other ImGui commands.
3. Do you mean the lines of the gizmo? I'll check if the underlying library `ImGuizmo` allows changing gizmo size.

**Comment by Seekerzero** [comment]
Thanks for the info! Regarding 3, Yes I mean the size of the gizmo, seems like currently it purely depends on the window's size.

**Comment by koide3** [comment]
I have added a few setters to `guik::ModelControl` (`set_gizmo_enabled(), set_gizmo_operation(), set_gizmo_mode(),`) https://github.com/koide3/iridescence/pull/101. `set_gizmo_clip_scale()` allows changing the size of the gizmo.

I updated ImGuizmo to the latest one because the clip space interface was only available on a newer version. I briefly tested the newer ImGuizmo on my environment, but I would appreciate if you could see if it works in your env. I noticed that the latest version exposes some gizmo properties that look fun to change (e.g., line colors and styles). I'll see if they can be added to `guik::ModelControl`.

**Comment by Seekerzero** [comment]
Hi Koide, 
going back to the previous question, you said that if I want to remove the Gizmo, just simply don't call the `draw_ui()` function. However, my implementation was inside a `subviewer->register_ui_callback()`, seems like currently, it doesn't have any method to remove an existing callback. Could you give me some suggestions on that?

**Comment by koide3** [comment]
Thanks for testing. I'll merge it.

> Could you give me some suggestions on that?

I meant you can do something like this to show/hide `ModelControl`:

```cpp
bool show = true;
guik::ModelControl model_control("model_matrix");

viewer->register_ui_callback("ui_callback", [&] {
  ImGui::Checkbox("show", &show);
  if (show) {
    model_control.draw_gizmo();
  }
});
```

You can also remove a callback by giving `0` (e.g., `viewer->register_ui_callback("cb_to_remove", 0);`). It's not intuitive, and I will add a more explicit interface like `remove_ui_callback()`.

**Comment by Seekerzero** [comment]
Thanks for the info! Like we see in your example, it would really make sense in the callback that we frequently update. But in the case that the callback only called once when it is initialized, there isn't a way to turn off the draw_gizmo (in my case, the `draw_gizmo()` was called inside a callback from subviewer, there isn't a big difference from just remove the callback). But it is not a big deal to me, and I think it also makes sense.

Thanks again! I think we can also close this issue once there aren't any new features being added to the plan.
