### ISSUE TITLE
Frustum drawing is broken

### ISSUE THREAD

**Issue by ymd-stella** [koide3/iridescence#92]
The following code appears to be trying to draw a line segment.
It looks like it expects to use GL_LINES.

https://github.com/koide3/iridescence/blob/085322e0c949f75b67d24d361784e85ad7f197ab/include/glk/primitives/frustum.hpp#L23-L32

However, it is actually drawn with GL_TRIANGLES.

https://github.com/koide3/iridescence/blob/085322e0c949f75b67d24d361784e85ad7f197ab/src/glk/mesh.cpp#L150

As a result, frustum is drawn as follows.

![image](https://github.com/koide3/iridescence/assets/7959916/020bba9d-f278-435f-9a44-e1f60dd30db0)

**Comment by ymd-stella** [comment]
If you want to draw using GL_TRIANGLES, the following code works fine.

```c++
    // bottom
    indices.push_back(0);
    indices.push_back(4);
    indices.push_back(1);

    // left
    indices.push_back(1);
    indices.push_back(4);
    indices.push_back(2);

    // top
    indices.push_back(2);
    indices.push_back(4);
    indices.push_back(3);

    // right
    indices.push_back(3);
    indices.push_back(4);
    indices.push_back(0);

    // front (1)
    indices.push_back(0);
    indices.push_back(1);
    indices.push_back(2);

    // front (2)
    indices.push_back(0);
    indices.push_back(2);
    indices.push_back(3);
```

![image](https://github.com/koide3/iridescence/assets/7959916/376a00db-5b68-4a22-b554-86c22b32f6ad)

**Comment by koide3** [comment]
Ah, thank you for finding and reporting the issue. I'll soon update the code as your suggestion accordingly. Thanks!

**Comment by koide3** [comment]
I noticed that it adds the front face as in the following screenshot. To keep the appearance of wire_frustum unchanged, I added an option for `glk::Frustum` to switch if closing the front face. I also added the solid frustum as a new primitive type. The PR https://github.com/koide3/iridescence/pull/94 will soon be merged after it passes the CI. Thanks again for reporting the issue.

![ss_1711894110 777477](https://github.com/koide3/iridescence/assets/31344317/bc1342c9-b986-4d6c-98f0-331ea435190b)

**Comment by ymd-stella** [comment]
If the front face is not closed, it disappears when viewing from the front.

![image](https://github.com/koide3/iridescence/assets/7959916/8d36648a-8bf8-4c02-81ef-51767591db2c)
![image](https://github.com/koide3/iridescence/assets/7959916/4143a66c-9158-40b3-b479-7073526f96aa)

When the front face is closed, I can see the frame from the front.

![image](https://github.com/koide3/iridescence/assets/7959916/a592b4b5-9acd-47fc-a6ac-d7197b000316)

Is the drawing result dependent on some setting?
