### ISSUE TITLE
Drawing thin_lines is affecting wireframes

### ISSUE THREAD

**Issue by ymd-stella** [koide3/iridescence#98]
Drawing thin_lines is affecting wireframes.

https://github.com/koide3/iridescence/assets/7959916/ae01a8ba-644b-4cf6-a979-5d02be82e7f0

Is it necessary to set the line width back to default(1.0)?

https://github.com/koide3/iridescence/blob/0172a680ce34de115049606a2b45aa6152732e11/src/glk/thin_lines.cpp#L64

**Comment by koide3** [comment]
Thanks for reporting the issue. I fixed it with https://github.com/koide3/iridescence/pull/99. I also added an option to change the line width of wireframe meshes.
